name: pip-wheels

on:
  schedule:
    - cron: "0 20 * * 5"
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04]
        python-version: ["3.9"]
        compiler: ["clang-13"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.4

      - name: Install Ubuntu dependencies
        env:
          COMPILER: ${{ matrix.compiler }}
        run: bash $GITHUB_WORKSPACE/.github/install_ubuntu_dependencies.sh

      - name: Add python requirements
        run: python -m pip install --upgrade wheel setuptools && python -m pip install -r requirements.txt

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
      
      