name: ubuntu22

on:
  workflow_dispatch:
 # push:
 #   branches:
 #     - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]
        python-version: ["3.9","3.10"]
        compiler: ["clang-12"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Ubuntu dependencies
        env:
          COMPILER: ${{ matrix.compiler }}
        run: bash $GITHUB_WORKSPACE/.github/install_ubuntu_dependencies.sh

      - run: sudo apt-get install patchelf

      - name: Add python requirements
        run: python -m pip install --upgrade wheel setuptools && python -m pip install -r requirements.txt

      - run: pip install auditwheel

      - name: "Create build directory and run CMake"
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DPIP_INSTALL=True

      - name: "Build Project" 
        run: cmake --build build --target _depreltest pypiwheel --config Release -- -j1 
      
      - name: Audit Wheel Test
        run:  auditwheel show build/pypiwheel/depreltest/dist/*.whl
      - name: Audit Wheel Patch
        run:  auditwheel repair --plat manylinux_2_31_x86_64 build/pypiwheel/depreltest/dist/*.whl






      
      #- name: 'upload artifact'
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: dist ${{ matrix.python-version }} ${{ matrix.platform }}
      #    path: build/pypiwheel/depreltest/dist
      #    retention-days: 1

      #- name: publish package to testpypi
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    password: ${{ secrets.test_pypi_api_token }}
      #    repository_url: https://test.pypi.org/legacy/
      #    packages_dir: build/pypiwheel/depreltest/dist