name: windows

on:
  push:
    branches:
      - main



env:
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19078/w_BaseKit_p_2023.0.0.25940_offline.exe
  
  WINDOWS_CPP_COMPONENTS: intel.oneapi.win.mkl.devel
 
  CACHE_NUMBER: 5
  SAMPLES_TAG: 2023.0.0
  COMPILER_VERSION: 2023.0.0
  TBB_VERSION: 2021.8.0
  VS_VER: vs2022
  ONEAPI_ROOT: C:/Program Files (x86)/Intel/oneAPI/

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        python-version: ["3.9"]
        compiler: ["clang-cl"]

    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:

      - name: install mkl
        run: scripts/windowsoneapi_install.bat $WINDOWS_BASEKIT_URL $WINDOWS_CPP_COMPONENTS
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Add python requirements
        run: python -m pip install --upgrade wheel setuptools && python -m pip install -r requirements.txt

      - name: "Create build directory and run CMake"
        run: cmake -S . -B build -G "Visual Studio 17 2022" -T "ClangCl" -DCMAKE_BUILD_TYPE=Release -DPIP_INSTALL=True

      - name: "Build Project" 
        run: cmake --build build --target _depreltest pypiwheel --config Release -- -j1 
      
